### ISSUE TITLE
Homebrew + Versioning

### ISSUE THREAD

**Issue by bahlo** [Lorenzo45/AutoMute#5]
Please version your builds to make it easier to manage with [Homebrew Cask](http://caskroom.io).

**Comment by timche** [comment]
Any chances that you can do this @Lorenzo45? I would like to install AutoMute via `brew cask`.

**Comment by Lorenzo45** [comment]
I haven't looked into this yet but it looks like it would be really convenient! I'm really busy with school right now so I likely won't be able to get around to this any time soon unfortunately.

**Comment by bahlo** [comment]
It would be enough to just create a release in GitHub on the latest `master` commit (in this case `v1.1`).

**Comment by Lorenzo45** [comment]
@bahlo Done, can't believe I didn't know about this feature before! Thanks!

**Comment by bahlo** [comment]
See https://github.com/caskroom/homebrew-cask/pull/20221. :ok_hand:
