### ISSUE TITLE
Can't get it to work [El Capitan]

### ISSUE THREAD

**Issue by vikeri** [Lorenzo45/AutoMute#6]
The app starts but when I try to click on for example mute it does nothing. The app doesn't react on any mouse clicks. Haven't developed for Mac so I don't know what logs that you might be interested in to be able to debug.

**Comment by Lorenzo45** [comment]
Oh wow, I'm seeing the same thing! Thanks for letting me know.

**Comment by einraum-design** [comment]
Same Problem (Also El Capitan - Version 10.11.2)

**Comment by Lorenzo45** [comment]
I believe I've isolated the issue for the setup window not working. Here's my StackOverflow question: http://stackoverflow.com/questions/34486264/clicking-nssegmentedcontrol-in-unselected-nstableview-row-always-produces-1-as 

If anyone has any input it'd be greatly appreciated!

**Comment by Lorenzo45** [comment]
Fixed by changing NSSegmentedCell to NSPopUpButtonCell
